deep_lesion:
  train:
    batch_size: 2
    dataset_type: deep_lesion
  test:
    batch_size: 8
    dataset_type: deep_lesion
    #dataset_dir: data/deep_lesion/test #here is the path of test sample
    #dataset_dir: ../complete/test #here is the path of test sample
    #dataset_dir: ../test
    dataset_dir: data/deep_lesion/train
    partial_holdout: 0.0
    random_mask: False
    random_flip: False
    load_mask: True